@baseUrl = http://localhost:3000
@contentType = application/json

POST {{baseUrl}}/graphql
Content-Type: {{contentType}}
X-REQUEST-TYPE: GraphQL

query {
  user(_id: "65b6c5c0ac96c6c541f902c1") {
    _id
    email
  }
}

