@baseUrl = http://localhost:3000/graphql

# @name createUser
POST {{baseUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateUser(updateUserInput: {
    email: "updated@example.com",
  }) {
    _id
    email
  }
}
